apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml

namespace: default

images:
- name: wildfly-test
  newName: divand/wildfly-test
  newTag: d4d3cc7b4d1ad758b5b7861e4a0c3a5b9d4eb81b
